apiVersion: v1
kind: Service
metadata:
  name: ada-backend-service
  namespace: ada-backend
spec:
  type: ClusterIP
  selector:
    app: ada-backend
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
