apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ada-backend
  name: ada-backend
  namespace: ada-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ada-backend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ada-backend
    spec:
      containers:
      - image: 572509365991.dkr.ecr.us-east-1.amazonaws.com/ada-backend:latest
        name: ada-backend
        resources: {}
status: {}
