spring:
  application:
    name: letscode-by-ada
  profiles: default, local, develop
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    url: jdbc:mysql://ada-database.ch7yon1jnlkb.us-east-1.rds.amazonaws.com:3306/adaDatabase
    username: ada_admin
    password: senhaDoBanco

security:
  oauth2:
    client:
      scope: password
  jwt:
    signing-key: Y2FiZcOnYSBkYSBvbsOnYQ==